### ISSUE TITLE
AZ of grafana persistent volume pvc should be based on the nodes' AZ

### ISSUE THREAD

**Issue by kukikiloke** [deis/monitor#196]
Cloud provider: AWS

When using persistent volume for grafana, one of my pods is stuck at pending state due to error `pod (deis-monitor-grafana-465911159-nkhmp) failed to fit in any node fit failure summary on nodes : NoVolumeZoneConflict (2), PodToleratesNodeTaints (1)`. The followings are the AZs my AWS resources running on:
```
Master: us-east-1a
Nodes: us-east-1c, us-east-1d
Dynamic pvc Volume: us-east-1a
```

I tried to manually attach the PVC volume on AWS console and it only allows me to choose EC2 instance from the same AZ as the volume. At this moment, the monitor charts create the volume to be at the same AZ as the master (just my guess, haven't looked into source code). Instead, it should be based on which AZ is/are the node(s) is hosted.

**Comment by kukikiloke** [comment]
may be related to https://github.com/deis/monitor/issues/188

**Comment by jchauncey** [comment]
When you install the monitor chart kubernetes is what requests the resources from AWS. The scheduler should bind the volume to the node that is requesting the PVC. If you do a `kubectl describe` on the persistent volume claim and the pod you should see which node it binds to.

**Comment by kukikiloke** [comment]
I may have missed it but I don't really see which node the pvc and pod bind to.

```
➜ kubectl describe pvc deis-monitor-grafana -n deis                                    
Name:		deis-monitor-grafana
Namespace:	deis
StorageClass:	
Status:		Bound
Volume:		pvc-dfdbea74-3431-11e7-9c85-0e796e66df3e
Labels:		heritage=deis
Annotations:	pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.alpha.kubernetes.io/storage-class=default
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Capacity:	5Gi
Access Modes:	RWO
Events:		<none>
```

```
➜ kubectl describe po -n deis --selector=app=deis-monitor-grafana
Name:		deis-monitor-grafana-465911159-qjl0w
Namespace:	deis
Node:		/
Labels:		app=deis-monitor-grafana
		pod-template-hash=465911159
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"deis","name":"deis-monitor-grafana-465911159","uid":"e0f6f19b-3431-11e7-9c85-0e79...
Status:		Pending
IP:		
Controllers:	ReplicaSet/deis-monitor-grafana-465911159
Containers:
  deis-monitor-grafana:
    Image:	quay.io/deis/grafana:v2.9.0
    Port:	3500/TCP
    Environment:
      INFLUXDB_URLS:		http://$(DEIS_MONITOR_INFLUXAPI_SERVICE_HOST):$(DEIS_MONITOR_INFLUXAPI_SERVICE_PORT_TRANSPORT)
      BIND_PORT:		3500
      DEFAULT_USER:		admin
      DEFAULT_USER_PASSWORD:	admin
      ALLOW_SIGN_UP:		true
    Mounts:
      /var/lib/grafana from grafana-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tzrm0 (ro)
Conditions:
  Type		Status
  PodScheduled 	False 
Volumes:
  grafana-data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	deis-monitor-grafana
    ReadOnly:	false
  default-token-tzrm0:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-tzrm0
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  6m		1m		22	default-scheduler			Warning		FailedScheduling	pod (deis-monitor-grafana-465911159-qjl0w) failed to fit in any node
fit failure summary on nodes : NoVolumeZoneConflict (2), PodToleratesNodeTaints (1)
```

**Comment by jchauncey** [comment]
Do a describe on the persistent volume itself

**Comment by kukikiloke** [comment]
here is what I got from describing the persistent volume

```
➜ kubectl describe pv -n deis                      
Name:		pvc-dfdbea74-3431-11e7-9c85-0e796e66df3e
Labels:		failure-domain.beta.kubernetes.io/region=us-east-1
		failure-domain.beta.kubernetes.io/zone=us-east-1a
Annotations:	kubernetes.io/createdby=aws-ebs-dynamic-provisioner
		pv.kubernetes.io/bound-by-controller=yes
		pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
StorageClass:	
Status:		Bound
Claim:		deis/deis-monitor-grafana
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	5Gi
Message:	
Source:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	aws://us-east-1a/vol-01489e5dd9ca52d8b
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
Events:		<none>

... other volume ...
```
